test without confirm pass

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,4 +1,4 @@
-name: test
+name: Run tests
 on:
   push:
     branches: [master]
@@ -522,20 +522,20 @@ jobs:
           path: >-
             test.tap
 
-  confirm-pass:
-    runs-on: self-hosted
-    needs: [prettier, editorconfig, pytest-changes, nf-core-lint, pytest, nf-test-changes, nf-test]
-    if: always()
-    steps:
-      - name: All tests ok
-        if: ${{ success() || !contains(needs.*.result, 'failure') }}
-        run: exit 0
-      - name: One or more tests failed
-        if: ${{ contains(needs.*.result, 'failure') }}
-        run: exit 1
+  # confirm-pass:
+  #   runs-on: self-hosted
+  #   needs: [prettier, editorconfig, pytest-changes, nf-core-lint, pytest, nf-test-changes, nf-test]
+  #   if: always()
+  #   steps:
+  #     - name: All tests ok
+  #       if: ${{ success() || !contains(needs.*.result, 'failure') }}
+  #       run: exit 0
+  #     - name: One or more tests failed
+  #       if: ${{ contains(needs.*.result, 'failure') }}
+  #       run: exit 1
 
-      - name: debug-print
-        if: always()
-        run: |
-          echo "toJSON(needs) = ${{ toJSON(needs) }}"
-          echo "toJSON(needs.*.result) = ${{ toJSON(needs.*.result) }}"
+  #     - name: debug-print
+  #       if: always()
+  #       run: |
+  #         echo "toJSON(needs) = ${{ toJSON(needs) }}"
+  #         echo "toJSON(needs.*.result) = ${{ toJSON(needs.*.result) }}"
